# Generated by Django 2.1.7 on 2019-03-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('contactnumber', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
