# Generated by Django 2.1.7 on 2019-03-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('collegename', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('quries', models.CharField(max_length=200)),
            ],
        ),
    ]
