# Generated by Django 2.1.7 on 2019-03-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='courseid',
            field=models.IntegerField(),
        ),
    ]
