# Generated by Django 2.1.7 on 2019-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190327_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='courseid',
            field=models.CharField(max_length=10),
        ),
    ]
