# Generated by Django 2.1.7 on 2019-03-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addworkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(max_length=10, unique=True)),
                ('professor', models.CharField(max_length=15)),
                ('timings', models.TimeField(max_length=5)),
                ('maxstrength', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
